### ISSUE TITLE
Projeto

### ISSUE THREAD

**Issue by devigor** [wbruno/livro-nodejs#1]
Gostaria de saber se ao decorrer do livro você mostra com construir uma aplicação com Node?

**Comment by wbruno** [comment]
Oi @IgorCorp, demonstro sim. No capítulo 5 é criada uma API com um crud completo (GET, POST, PUT e DELETE) com o banco de dados MongoDB.
Os outros capítulos são sobre o NodeJS, REST, Testes, um básico de javascript e ecma6..

**Comment by devigor** [comment]
Entendi.
Outra pergunta: você usa muito Javascript OO no livro?? Bastar apenas essa pergunta para eu adquirir o livro

**Comment by wbruno** [comment]
Sim, utilizo JavaScript OO, como você pode ver por este arquivo (Função Construtora):
https://github.com/wbruno/livro-nodejs/blob/master/capitulo_5/capitulo_5.13.2/controllers/StormtropperController.js

No capítulo 1, ainda mostro como seria Objeto Literal e Função Construtora, sendo que você pode utilizar qualquer um dos dois métodos.

**Comment by devigor** [comment]
Obrigado pela atenção.
Livro adquirido!
