### ISSUE TITLE
Capítulo 5 - Construindo uma API RESTfull com Express

### ISSUE THREAD

**Issue by Cmcampos86** [wbruno/livro-nodejs#3]
Boa tarde!

Estou no capítulo 5.9.1 e tenho dúvidas o que seria um wrapper (no caso é citado... construir um wrapper com o módulo MongoJS).

Tentei procurar o que seria um wrapper mas não compreendi muito muito.

O que seria exatamente?

**Comment by wbruno** [comment]
wrapper no livro é uma **abstração** em cima de outra coisa, no caso, em cima do conector do mongodb.

**Comment by Cmcampos86** [comment]
Legal!
Entendi!

Obrigado!
