### ISSUE TITLE
Capítulo 2 - chat TCP

### ISSUE THREAD

**Issue by gabsprates** [wbruno/livro-nodejs#5]
Olá,

Confesso que não entendi o `clientList.indexOf(5)` da [linha 8 no arquivo do chat](https://github.com/wbruno/livro-nodejs/blob/master/capitulo_2/capitulo_2.8/chat-tcp.js#L8).

Isso está certo? Deveria ser **5** mesmo ou era pra ser algo relacionado à variável `data` do escopo dessa função?

**Comment by wbruno** [comment]
Oi @gabsprates ! foi erro meu.. o correto é assim:

``` javascript
'use strict';

var net         = require('net'),
    chatServer  = net.createServer(),
    clientList  = [];


var broadcast = function (message, client) {
  for (var i = clientList.length - 1; i >= 0; i--) {
    if (client !== clientList[i]) {
      clientList[i].write(message);
    }
  }
};

chatServer.on('connection', function (client) {
  client.write('Hi guest' + '!\n');
  clientList.push(client);

  client.on('data', function (data) {
    broadcast(data, client);
  });
  client.on('end', function () {
    console.log('client', clientList.indexOf(client));

    clientList.splice(clientList.indexOf(client), 1);
  });
  client.on('error', function(err) {
    console.log(err);
  });
});

chatServer.listen(9000);
```

**Comment by gabsprates** [comment]
Ah sim! Agora eu entendi (:
Obrigado.

Onde eu acho uma lista com os eventos `.on()` do `net.createServer();`?

**Comment by wbruno** [comment]
aqui:
https://nodejs.org/dist/latest-v7.x/docs/api/net.html

**Comment by gabsprates** [comment]
Opa, eu não tinha reparado nas seções "Event: " :laughing: 

Valeu (:
