### ISSUE TITLE
Capítulo 5 - Banco de Dados MongoDB

### ISSUE THREAD

**Issue by gabsprates** [wbruno/livro-nodejs#6]
Olá @wbruno,

Eu estava lendo o capítulo 5 outra vez e me perguntei, "por que não usar o [node-mongodb-native](https://github.com/mongodb/node-mongodb-native)?", daí te faço essa pergunta. 

Seria mais complicado? Por que você não usou aqui?

**Comment by wbruno** [comment]
Oi @gabsprates !
Eu prefiro usar o mongojs porque a sintaxe dele é idêntica a sintaxe do terminal do mongodb.
No mongo você faz:
db.stormtroopers.delete()
e não
.deleteOne()
ou 
.insertMany()
entende?

não curto abstração em cima de abstração, e no mongojs você usa:
db.collection('stormtroopers').delete()
o que faz mais sentido e é mais próximo do que o mongo usa.

mas poderia usar, sem problemas. Só não usei mesmo para não ter esse "de->para" de funções.

**Comment by gabsprates** [comment]
Saquei, bacana.
\o
