### ISSUE TITLE
Ecmascript e o jest.

### ISSUE THREAD

**Issue by emanoelantonio** [wbruno/livro-nodejs#8]
Fala @wbruno tudo ok? Bom, primeiro dizer que adorei seu livro de node 😄 . Quero compartilhar um erro que estou tomando ao executar o jest.
`ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.`
Poderia me dizer como solucionar?

**Comment by wbruno** [comment]
Oi @emanoelantonio desculpa a demora
compartilha alguns arquivos para eu reproduzir o erro?

preciso ver como está.
